// Copies the Font Awesome Pro icons the site uses out of the licensed kit in
// vendor/ (gitignored) into components/icons/fa-data.ts, which is committed.
// Pro files may not be redistributed, so only add icons that are in use.
// Run with `npm run icons` after editing ICONS.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ICONS = [
  "solid/house",
  "regular/house",
  "solid/briefcase",
  "regular/briefcase",
  "solid/square-info",
  "regular/square-info",
  "solid/screwdriver-wrench",
  "regular/screwdriver-wrench",
  "solid/address-card",
  "regular/address-card",
  "solid/message-lines",
  "regular/message-lines",
  "solid/file-lines",
  "regular/file-lines",
  "solid/arrow-left",
  "solid/arrow-right",
  "solid/arrow-up-right",
  "solid/arrow-down-to-line",
  "duotone/hand-pointer",
];

const root = join(import.meta.dirname, "..");
const kit = join(root, "vendor/fontawesome-pro/svgs");

let attribution = "";
const entries = ICONS.map((id) => {
  const svg = readFileSync(join(kit, `${id}.svg`), "utf8");
  attribution ||= svg.match(/<!--!\s*(.*?)\s*-->/)?.[1] ?? "";
  const [, , , w, h] = svg.match(/viewBox="(\S+) (\S+) (\S+) (\S+)"/).map(Number);
  const paths = [...svg.matchAll(/<path(?: class="([^"]+)")? d="([^"]+)"/g)];
  const find = (cls) => paths.find((p) => p[1] === cls)?.[2];
  const icon = id.startsWith("duotone/")
    ? { w, h, d: find("fa-primary"), secondary: find("fa-secondary") }
    : { w, h, d: paths[0][2] };
  if (!icon.d) throw new Error(`No path found in ${id}.svg`);
  return `  ${JSON.stringify(id)}: ${JSON.stringify(icon)},`;
});

writeFileSync(
  join(root, "components/icons/fa-data.ts"),
  `/*! ${attribution} */
// Generated by scripts/build-icons.mjs. Do not edit by hand.

export const faIcons = {
${entries.join("\n")}
} as const;
`,
);

console.log(`Wrote ${ICONS.length} icons to components/icons/fa-data.ts`);
